version: '3.8'

services:
  api:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
